# This is a basic workflow to help you get started with Actions

name: Automatically assign reviewers

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [opened]
    branches: [ master, devel ]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - uses: shufo/auto-assign-reviewer-by-issuer@v1.0.0
      with:
        config: '.github/workflows/reviewers.yml'
        token: ${{ secrets.GITHUB_TOKEN }}





###################################
# This is a basic workflow to help you get started with Actions

#on:
#  pull_request:
#    branches: [ devel ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
#jobs:
#  add_reviewers:
    # The type of runner that the job will run on
#    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
#    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#    - uses: actions/checkout@v2

#    - name: Review Request Action
#      uses: kunihiko-t/review-request-action@v0.1.3
#      with:
        # Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
#        repo-token: ${{ secrets.GITHUB_TOKEN }}
        # user names csv
#        reviewers: NicolasLiampotis, Tas-sos
        # optional
        # team names csv
        #team-reviewers: # optional
